# Generated by Django 3.0.5 on 2020-05-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('used_year_number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'skill',
            },
        ),
    ]
