# Generated by Django 3.0.5 on 2020-05-12 18:09

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('is_activate', models.BooleanField(default=False)),
                ('avatar', models.ImageField(upload_to='images/', verbose_name='avatar')),
                ('birthday', models.DateTimeField()),
                ('skill', models.ManyToManyField(to='skill.Skill')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
